version: '3.9'

services:
  redis:
    image: redis

  video-chat:
    build: .
    platform: linux/amd64
    command: uvicorn DjangoVideoChat.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
